import { useState } from "react";
import { Card, CardBody, CardHeader, CardTitle } from "@/components/ui/SCard";
import { Chip } from "@/components/ui/SChip";
import { SButton } from "@/components/ui/SButton";
import { useStore } from "@/store/useStore";
import { RefreshCw, Sparkles, FileText } from "lucide-react";

function confTone(c: number) { return c >= 85 ? "green" : c >= 60 ? "amber" : "red"; }

export function Layer3Extraction() {
  const { fields, docs, currentSmeId, updateField, lang } = useStore();
  const smeDocs = docs.filter((d) => d.smeId === currentSmeId);
  const [activeDocId, setActiveDocId] = useState(smeDocs[0]?.id ?? docs[0].id);
  const activeDoc = docs.find((d) => d.id === activeDocId)!;
  const docFields = fields.filter((f) => f.docId === activeDocId);
  const [shimmer, setShimmer] = useState(false);

  const reextract = () => {
    setShimmer(true);
    setTimeout(() => {
      docFields.forEach((f) => {
        const newConf = Math.min(99, f.confidence + Math.floor(Math.random() * 8) + 2);
        updateField(f.id, { confidence: newConf, flagged: newConf < 80 });
      });
      setShimmer(false);
    }, 1200);
  };

  return (
    <div className="grid gap-6 p-6 lg:grid-cols-2">
      <Card>
        <CardHeader className="flex items-center justify-between">
          <CardTitle>{lang === "en" ? "Document Preview" : "ดูเอกสาร"}</CardTitle>
          <select
            value={activeDocId}
            onChange={(e) => setActiveDocId(e.target.value)}
            className="h-8 rounded-md border border-brand-border bg-brand-surface px-2 text-xs"
          >
            {docs.map((d) => <option key={d.id} value={d.id}>{d.filename}</option>)}
          </select>
        </CardHeader>
        <CardBody>
          <div className="mb-3 flex items-center gap-2">
            <Chip tone="green"><FileText className="h-3 w-3" />{activeDoc.type} — {activeDoc.confidence}%</Chip>
            <Chip tone="outline">{activeDoc.source}</Chip>
          </div>
          <div className={`relative aspect-[4/5] overflow-hidden rounded-lg border border-brand-border bg-white ${shimmer ? "shimmer" : ""}`}>
            <svg viewBox="0 0 400 500" className="h-full w-full">
              <rect width="400" height="500" fill="#f8f8f5" />
              <text x="20" y="40" className="fill-slate-800" fontSize="20" fontWeight="700">PEA Provincial Electricity</text>
              <text x="20" y="62" className="fill-slate-500" fontSize="11">Tax Invoice / Receipt</text>
              <line x1="20" y1="78" x2="380" y2="78" stroke="#cbd5e1" />
              <text x="20" y="105" fontSize="11" className="fill-slate-500">Customer</text>
              <text x="20" y="125" fontSize="13" className="fill-slate-800">Siam Sustainable Textiles Co.</text>
              <text x="20" y="160" fontSize="11" className="fill-slate-500">Billing Period</text>
              <rect x="18" y="168" width="120" height="22" fill="none" stroke="#00c97c" strokeWidth="1.5" />
              <text x="24" y="184" fontSize="13" fontWeight="600" className="fill-slate-900">2025-09</text>
              <text x="20" y="220" fontSize="11" className="fill-slate-500">Total kWh</text>
              <rect x="18" y="228" width="160" height="26" fill="none" stroke="#00c97c" strokeWidth="1.5" />
              <text x="24" y="247" fontSize="16" fontWeight="700" className="fill-slate-900">84,210 kWh</text>
              <text x="220" y="220" fontSize="11" className="fill-slate-500">Total Amount</text>
              <rect x="218" y="228" width="160" height="26" fill="none" stroke="#00c97c" strokeWidth="1.5" />
              <text x="224" y="247" fontSize="16" fontWeight="700" className="fill-slate-900">฿312,840.00</text>
              <text x="20" y="290" fontSize="11" className="fill-slate-500">Tariff Class</text>
              <rect x="18" y="298" width="120" height="22" fill="none" stroke="#ffb547" strokeWidth="1.5" />
              <text x="24" y="314" fontSize="13" className="fill-slate-900">Industrial 2.2</text>
              <text x="220" y="290" fontSize="11" className="fill-slate-500">Power Factor</text>
              <rect x="218" y="298" width="80" height="22" fill="none" stroke="#ff5e5e" strokeWidth="1.5" />
              <text x="224" y="314" fontSize="13" className="fill-slate-900">0.91</text>
              <line x1="20" y1="370" x2="380" y2="370" stroke="#cbd5e1" />
              <text x="20" y="395" fontSize="10" className="fill-slate-400">Signature</text>
              <text x="20" y="475" fontSize="9" className="fill-slate-400">Generated by SERI · OCR pipeline v0.9</text>
            </svg>
          </div>
        </CardBody>
      </Card>

      <Card>
        <CardHeader className="flex items-center justify-between">
          <CardTitle>{lang === "en" ? "Extracted Fields" : "ฟิลด์ที่สกัดได้"}</CardTitle>
          <SButton size="sm" variant="primary" onClick={reextract}>
            <RefreshCw className={`h-3.5 w-3.5 ${shimmer ? "animate-spin" : ""}`} />
            {lang === "en" ? "Re-extract" : "สกัดใหม่"}
          </SButton>
        </CardHeader>
        <CardBody className="p-0">
          <table className="w-full text-sm">
            <thead className="bg-brand-surface2 text-xs uppercase tracking-wider text-brand-text3">
              <tr>
                <th className="px-4 py-2 text-left">Field</th>
                <th className="px-4 py-2 text-left">Value</th>
                <th className="px-4 py-2 text-left">Conf</th>
                <th className="px-4 py-2 text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-brand-border">
              {docFields.map((f) => (
                <tr key={f.id} className="hover:bg-brand-surface2/50">
                  <td className="px-4 py-2.5 font-medium">{f.name}</td>
                  <td className="px-4 py-2.5 font-mono text-brand-text2">
                    {f.value} <span className="text-brand-text3">{f.unit}</span>
                  </td>
                  <td className="px-4 py-2.5"><Chip tone={confTone(f.confidence) as "green"|"amber"|"red"}>{f.confidence}%</Chip></td>
                  <td className="px-4 py-2.5 text-right">
                    <button className="text-xs text-brand-blue hover:underline">
                      {f.flagged ? (lang === "en" ? "Review" : "ตรวจ") : (lang === "en" ? "OK" : "โอเค")}
                    </button>
                  </td>
                </tr>
              ))}
              {docFields.length === 0 && (
                <tr><td colSpan={4} className="p-8 text-center text-brand-text3">No fields extracted yet</td></tr>
              )}
            </tbody>
          </table>
          <div className="border-t border-brand-border bg-brand-surface2/30 px-4 py-3 text-xs text-brand-text3">
            <Sparkles className="mr-1 inline h-3 w-3 text-brand-green" />
            {lang === "en"
              ? "Powered by Claude Vision + Tesseract fallback. Low-confidence fields auto-route to Layer 8."
              : "ใช้ Claude Vision + Tesseract สำรอง ฟิลด์ความมั่นใจต่ำส่งไป Layer 8 อัตโนมัติ"}
          </div>
        </CardBody>
      </Card>
    </div>
  );
}
